name: class_generator
description: Builder-based library for dart code generation such as classes, methods, properties and constructors.
version: 2.0.1
homepage: https://github.com/nathanielxd/dart-class-generator
environment:
  sdk: '>=2.15.0 <3.0.0'

dependencies:
  recase: ^4.0.0

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0