name: class_builder
description: A toolkit for dart code generation such as classes, methods, properties and constructors.
version: 1.0.0
homepage: https://github.com/nathanielxd/class-builder
environment:
  sdk: '>=2.15.0 <3.0.0'

dependencies:
  recase: ^4.0.0

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0